apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: campustest-api
  namespace: campustest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: campustest-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 65 }
    - type: Resource
      resource:
        name: memory
        target: { type: Utilization, averageUtilization: 75 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: campustest-web
  namespace: campustest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: campustest-web
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: campustest-worker
  namespace: campustest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: campustest-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
